# Generated by Django 3.0.5 on 2020-06-12 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='task_id',
            field=models.UUIDField(default=uuid.UUID('85c2d554-ac9a-11ea-903e-0242ac130006')),
        ),
    ]
