# Generated by Django 3.0.5 on 2020-06-12 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alarm_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='task_id',
            field=models.UUIDField(default=uuid.UUID('67f36e38-ac9c-11ea-986d-0242ac130006'), unique=True),
        ),
    ]
