# Generated by Django 3.0.5 on 2020-06-12 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200612_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid1, unique=True),
        ),
    ]
