version: '3'

services:

  nginx:
    image: nginx
    environment:
      - VIRTUAL_HOST=${BDG_PUBLIC_HOST}
      - VIRTUAL_PORT=80
    depends_on:
      - server

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./aurore/src/static:/usr/share/nginx/html/static:ro

  server:
    environment:
      - HOST=${BDG_SERVER_HOSTNAME}
      - PUBLIC_HOST=${BDG_PUBLIC_HOST}
      - SECRET_KEY=${BDG_SECRET_KEY}
      - SERVER_DEBUG=${BDG_SERVER_DEBUG}
      - SV_PWD=${BDG_SV_PWD}
    build:
      context: ./aurore
      dockerfile: Dockerfile.dev
    volumes:
      - ./aurore:/usr/src/aurore


networks:
  default:
    external:
      name: nginx-proxy

  #https://www.howtoforge.com/tutorial/docker-guide-dockerizing-python-django-application/
  #https://github.com/sovanna/bootstrap-django-gatsby/blob/master/docker-compose.dev.yml